### ISSUE TITLE
error when creating token

### ISSUE THREAD

**Issue by togonow** [bennypowers/stripe-elements#2] opened 2017-08-15 07:53 UTC
I'm getting an error at the catch error for line 299 of stripe-elements/stripe-elements.html:
 this._stripe.createToken(this._card).then((result) => {

 }).catch((error) => {

}

Uncaught (in promise) Error: You must provide a Stripe Element or a valid token type to create a Token.

**Comment by bennypowers** [comment] 2017-08-15 11:53
Please provide steps to reproduce, thanks.

**Comment by togonow** [comment] 2017-08-15 21:35
I stripped the project to the bare minimum to simulate the way i'm using it in my project. The temp repository is available at  @ https://github.com/togonow/se  
in chrome, i'm getting the same error from /bower_components/stripe-elements line 282 when i press submit: 
"We could not retrieve data from the specified Element.
              Please make sure the Element you are attempting to use is still mounted."
below is a chrome dev snapshot

![image](https://user-images.githubusercontent.com/4708158/29337638-d91ae522-81c6-11e7-8a20-54597e33c4fa.png)

**Comment by bennypowers** [comment] 2017-08-16 11:24
Ok I was able to reproduce. AFAIK this only happens on Polymer 2.0. I'll continue to investigate

**Comment by togonow** [comment] 2017-08-16 22:22
Hey, I tried to follow stripe.com guide (quick start code samples) and integrate their snippets in my existing polymer 2 project. I faced the same issue, seems it's related to them using card.mount and polymer 2

**Comment by togonow** [comment] 2017-08-17 00:41
Eureka, (i guess) I went thru the freenode #stripe chat history log. @polymer had a working version  on js fiddle back in june 27 https://jsfiddle.net/testing_polymer_2/7r5ajt00/ 
basicly u have to force shady dom using: 
<script>
  ShadyDOM = {
    force: true
  }

</script>
but not sure if that will persist to other components, looking into that!!

![image](https://user-images.githubusercontent.com/4708158/29391136-cdb1ec24-82a9-11e7-816a-9d753b941d1f.png)

**Comment by bennypowers** [comment] 2017-08-21 06:22
forcing shady dom is a less-than-ideal solution :/

**Comment by togonow** [comment] 2017-08-21 06:59
yeah, i think we need to reach out to the polymer guys, but they hardly respond to tedious issue. I noticed you posted on Stripe freenode, any luck with that?

**Comment by bennypowers** [comment] 2017-08-21 14:03
They were unfamiliar with polymer, so they didn't comment. I'd like to find out more about exacly why and how this is failing

**Comment by nwams** [comment] 2017-08-23 01:54
I'm also experiencing the "We could not retrieve data from the specified Element. Please make sure the Element you are attempting to use is still mounted" error. 

But the error only happens in Chrome. Safari and Firefox work fine and return a token.

**Comment by togonow** [comment] 2017-08-23 23:24
Haven't tested outside of chrome, kind of didn't expect it to work anywhere else, will test that tomorrow

**Comment by nwams** [comment] 2017-08-24 15:28
@bennypowers curious, do you know what is is that allows your element to still work when I demo it on the [WebComponents site](https://www.webcomponents.org/element/bennypowers/stripe-elements)?

**Comment by bennypowers** [comment] 2017-08-24 15:42
@nwams could be that the demo there is running polymer 1

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nwams** [comment] 2017-08-24 15:58
@bennypowers I thought the same for a bit, but I checked your bower.json file and I'm also on Polymer 1. Polymer 1 is having the same mounting error for me as well as well. It's difficult for me to tell whether this is a Polymer-specific issue or a Stripe-specific issue. 
The strange thing is I had it working a few months ago, then one day all of a sudden, without any changes on my end it started giving this mount error.

**Comment by bennypowers** [comment] 2017-08-24 16:04
Try it with shady Dom polyfill. Based on the investigations above it sounds like it might be a shadow Dom thing. Stripe elements are written in react, and at the summit, Rob Dodson published custom elements everywhere, which says react has problems crossing the shadow boundary.

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nwams** [comment] 2017-08-30 17:14
@bennypowers I'm not sure how to apply shady Dom polyfill to the stripe-elements in Polymer 1. Do you have an example of how to do this?

**Comment by bennypowers** [comment] 2017-09-06 04:59
To enable shady dom in your app, add this to index.html, before you import polymer.html

```html
  <script>
    /* this script must run before Polymer is imported */
    window.Polymer = {
      dom: 'shady',
      lazyRegister: true
    };
  </script>
```
It's not perfect but hopefully it will work in a pinch

**Comment by MrPhishfood** [comment] 2017-09-10 15:11
Glad I'm not the only one with this bug. It works in Firefox and Edge, but not Chrome and Opera. I also suspect it's happening only on browsers with native shadow DOM.

**Comment by mlabarre** [comment] 2017-10-03 06:53
Generalize Polyfill only for a Stripe problem. It's a dream !

**Comment by morbidick** [comment] 2017-10-05 14:06
@mlabarre i started working on a version talking directly with the stripe api, still needs tests but should do the trick for now https://github.com/morbidick/stripe-elements

**Comment by atifwaqar** [comment] 2017-10-07 20:18
I am also facing "We could not retrieve data from the specified Element. Please make sure the Element you are attempting to use is still mounted."

**Comment by morbidick** [comment] 2017-10-07 23:02
You could take #7 for a spin it uses my before mentioned element as fallback.

**Comment by dspint** [comment] 2017-11-02 23:39
You shouldn't need to mess with around ShadyDom polyfills, etc.

This error happens because the Stripe code is looking for the `#card-element` in light dom. Since you're inside a Polymer component, the element is in shadowRoot instead (shadow dom).

So, you can create the insert wrapper dynamically and append to the lightdom instead:

```
const DIV = document.createElement('div');
const cardSlot = DIV.cloneNode();
cardSlot.setAttribute('slot', 'card');
// Create stripe card wrapper
let card = DIV.cloneNode();
card.id = 'card-element';
// Add wrapper to slot
cardSlot.appendChild(card);
// Append slot to light dom
this.appendChild(cardSlot);
...
card.mount(this.querySelector('#card-element'));
```

If `<stripe-elements>` is in turn init inside another component, then you'll have to do the same thing to it (and so forth up the chain) so that ultimately `<div id="card-element">` is in lightdom:

```
// In parent component shadowRoot (`<dom-module> -> <template>`)
// You can add manual slot to position the stripe element in relation to other shadowRoot elements
<slot name="stripe-card"></slot>
...
// Init Slot
const div = document.createElement('div');
div.setAttribute('slot', 'stripe-card');
// Create <stripe-elements> instance
const SE = document.createElement('stripe-elements');
// Add any attributes or text content here
// Append <stripe-elements> to slot
div.appendChild(zingCC);
// Append slot to parent component
this.appendChild(div);
```

**[NOTE]:** We didn't use `<stripe-elements>` so you may need to tweak the above for this component/lib. This just worked in our Polymer2 app with our own created components when we encountered this console error.

**Comment by zbury** [comment] 2017-11-10 10:12
I came up with a slightly more static approach that I think does the same thing as @dspint's solution. It's far from ideal, but better than forcing the shady DOM polyfill imo.

Instead of "exposing" the DOM that Stripe needs to work correctly by disabling shadow DOM, we can insert the DOM into a top-level element and use a series of cascading [slot elements assigned to a slot](https://www.polymer-project.org/2.0/docs/devguide/shadow-dom#multi-level-distribution) to "pierce" through multiple layers of shadow DOM. This works because child elements inserted into a parent's `slot` are in the parent's light DOM. 

For example, my top level element is an `app-shell`.

`index.html`
```
<body>
    <app-shell>Anything here is light DOM<app-shell>
</body>
```

To insert the `slot` content of `app-shell` into another custom element we simultaneously assign and declare a slot. This has the effect of "forwarding" on the light DOM from `index.html` to `checkout-page`.

`app-shell.html`
```
<iron-pages ...>
   ...
   <checkout-page><slot name="stripe-inputs" slot="stripe-inputs"></slot></checkout-page>
</iron-pages>
```
That process can be repeated as many times as needed until we reach the custom element that should actually display the content.

To display it, we just use a normal `slot`.

`checkout-page.html`
```
....
<slot name="stripe-inputs"></slot>
....
```

Obviously declaring all of our Stripe code inside index.html would be messy, instead we can declare the DOM inside a `template` element and "stamp" it with the [Polymer.TemplateStamp Mixin](https://www.polymer-project.org/2.0/docs/api/mixins/Polymer.TemplateStamp). The mixin allows you to do other cool things like declare event-handlers in the template that get handled by the stamping element, no matter where the template is in the DOM tree.

`checkout-page.html`
```
<link rel="import" href="../../bower_components/polymer/lib/mixins/template-stamp.html">
...
<template>
    <!-- checkout-page template -->
    ...

    <!-- this is where the #stripeInputs template will get "inserted" as light DOM -->
    <slot name="stripe-inputs"></slot>
   
    ...

    <template id="stripeInputs">
       <style>
           /* one benefit of using a template (as opposed to just a `div`) 
            is you can declare scoped styling here */
        </style>

        <div slot="stripe-inputs">
            <div id="card"></div>
        </div>
    </template>
</template>

class CheckoutPage extends Polymer.TemplateStamp(Polymer.Element) {
...
ready() {
    super.ready();

    // stamp stripe template
    const template = this._stampTemplate(this.$.stripeInputs);

    // append template to `app-shell` (as light DOM)
    const appShell = document.querySelector('app-shell');
    appShell.appendChild(template);
}
...
_initStripeElements() {
    const elements = Stripe.elements();
    const card = elements.create('card');
    card.mount('#card'); // we can use normal document selector
}
```

Haven't tested it a ton but seems to work fine in Chrome.

**Comment by jfdevradius** [comment] 2017-11-10 18:21
@zbury That solutions works. Thanks.

**Comment by kangby93** [comment] 2018-01-05 08:20
@zbury Your solution work for me as well! Thanks.

**Comment by bennypowers** [comment] 2018-01-13 22:23
@zbury please take a look at ddc737250b9a937613133cc9272d9416ab469213 where I apply your solution by automatically generating the slots. I was not quite able to get things running, however:

```
We could not retrieve data from the specified Element. Please make sure the Element you are attempting to use is still mounted.
```

Would you be interested in taking a look, maybe issuing a PR?

**Comment by bennypowers** [comment] 2018-01-14 18:40
649ea84b1930e6b13aa134e95f739bcd607a8823 Looks like it works. Closing.

**Closed by bennypowers** 2018-01-14 18:40 UTC
Labels: bug, help wanted

**Comment by nojvek** [comment] 2019-04-19 06:57
Using shadowDom, stripe still gives that error `We could not retrieve data from the specified Element. Please make sure the Element you are attempting to use is still mounted.`

**Comment by bennypowers** [comment] 2019-04-19 07:04
Thanks @nojvek for the report. I'll check this out after Passover. Please open a new issue with a reproduction.

**Comment by nojvek** [comment] 2019-04-19 07:05
Will try to get you a codepen repro
